apiVersion: v1
kind: Service
metadata:
  name: simple-apt-cacher-ng
  labels:
    name: simple-apt-cacher-ng
spec:
  type: LoadBalancer
  ports:
    - port: 3142
      targetPort: 3142
      protocol: TCP
  selector:
    name: simple-apt-cacher-ng
